-- Tables used by the Flask routes in backend/routes/*.py
-- Kept separate from the existing public.invoices schema to avoid collisions.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

-- Groups registered via POST /v1/auth/register
CREATE TABLE IF NOT EXISTS public.api_groups (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  group_name text NOT NULL UNIQUE,
  api_token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Invoice templates referenced by templateInvoice
CREATE TABLE IF NOT EXISTS public.api_templates (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  template_id text NOT NULL,
  owner_token text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT api_templates_owner_template_unique UNIQUE (owner_token, template_id)
);

-- Invoices created via POST /v1/invoices/generate
CREATE TABLE IF NOT EXISTS public.api_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_token text NOT NULL,
  template_id text NOT NULL,
  xml text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Enable RLS on all API tables. Policies below keep behaviour equivalent to
-- "RLS off" while allowing you to tighten access later if needed.
ALTER TABLE public.api_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_invoices ENABLE ROW LEVEL SECURITY;

-- Allow all roles full access for now (development-friendly).
-- You can later restrict these (e.g. TO service_role ONLY, or add predicates).
CREATE POLICY api_groups_all ON public.api_groups
  FOR ALL TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY api_templates_all ON public.api_templates
  FOR ALL TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY api_invoices_all ON public.api_invoices
  FOR ALL TO public
  USING (true)
  WITH CHECK (true);

-- Seed dev data to match the previous in-memory defaults.
INSERT INTO public.api_groups (group_name, api_token)
VALUES
  ('dev', 'abc123'),
  ('other', 'other_token')
ON CONFLICT DO NOTHING;

INSERT INTO public.api_templates (template_id, owner_token)
VALUES
  ('template1', 'abc123'),
  ('template2', 'other_token')
ON CONFLICT ON CONSTRAINT api_templates_owner_template_unique DO NOTHING;

-- Seed two invoices for token abc123 (IDs kept for compatibility with prior code).
INSERT INTO public.api_invoices (id, owner_token, template_id, xml)
OVERRIDING SYSTEM VALUE
VALUES
  (12345, 'abc123', 'template1', '<Invoice><ID>12345</ID></Invoice>'),
  (54321, 'abc123', 'template1', '<Invoice><ID>54321</ID></Invoice>')
ON CONFLICT DO NOTHING;

-- Ensure the identity sequence is >= the seeded max(id)
SELECT setval(
  pg_get_serial_sequence('public.api_invoices', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.api_invoices), 1),
  true
);

