-- Tables used by the Flask routes in backend/routes/*.py
-- Kept separate from the existing public.invoices schema to avoid collisions.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

-- Groups registered via POST /v1/auth/register
CREATE TABLE IF NOT EXISTS public.api_groups (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  group_name text NOT NULL UNIQUE,
  api_token text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Invoices created via POST /v1/invoices/generate
-- owner_token + template_id 
CREATE TABLE IF NOT EXISTS public.api_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_token text NOT NULL,
  template_id text NOT NULL,
  xml text NOT NULL,
  invoice_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted boolean NOT NULL DEFAULT false
);

-- Enable RLS on all API tables. Policies below keep behaviour equivalent to
-- "RLS off" while allowing you to tighten access later if needed.
ALTER TABLE public.api_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_invoices ENABLE ROW LEVEL SECURITY;

-- Allow all roles full access for now (development-friendly).
-- You can later restrict these (e.g. TO service_role ONLY, or add predicates).
CREATE POLICY api_groups_all ON public.api_groups
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY api_invoices_all ON public.api_invoices
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- Seed dev data to match the previous in-memory defaults.
INSERT INTO public.api_groups (group_name, api_token)
VALUES
  ('dev', 'abc123'),
  ('other', 'other_token')
ON CONFLICT DO NOTHING;

-- Seed two invoices for token abc123 (IDs kept for compatibility with prior code).
INSERT INTO public.api_invoices (id, owner_token, template_id, xml, invoice_data)
OVERRIDING SYSTEM VALUE
VALUES
  (12345, 'abc123', 'template1', '<Invoice><ID>12345</ID></Invoice>', '{}'::jsonb),
  (54321, 'abc123', 'template1', '<Invoice><ID>54321</ID></Invoice>', '{}'::jsonb)
ON CONFLICT DO NOTHING;

-- Ensure the identity sequence is >= the seeded max(id)
SELECT setval(
  pg_get_serial_sequence('public.api_invoices', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.api_invoices), 1),
  true
);

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
